// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/huffmanr.h"
#include <Rcpp.h>

using namespace Rcpp;

// internal_huffman_map
std::unordered_map<std::string, Node*> internal_huffman_map(NumericVector probabilities);
RcppExport SEXP huffmanr_internal_huffman_map(SEXP probabilitiesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type probabilities(probabilitiesSEXP );
        std::unordered_map<std::string, Node*> __result = internal_huffman_map(probabilities);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// huffman_encode
Environment huffman_encode(NumericVector probabilities);
RcppExport SEXP huffmanr_huffman_encode(SEXP probabilitiesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type probabilities(probabilitiesSEXP );
        Environment __result = huffman_encode(probabilities);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
