# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_huffman_map <- function(probabilities) {
    .Call('huffmanr_internal_huffman_map', PACKAGE = 'huffmanr', probabilities)
}

huffman_encode <- function(probabilities) {
    .Call('huffmanr_huffman_encode', PACKAGE = 'huffmanr', probabilities)
}

